import { NextRequest, NextResponse } from "next/server";

const REQUIRED_FIELDS = [
  "fullName",
  "email",
  "phone",
  "retreat",
  "emergencyContactName",
  "emergencyContactPhone",
  "waiverAcknowledged",
];

// --- CRM connector -----------------------------------------------------
// Once the Salty Skins CRM exposes an API endpoint + token for creating
// applications, set these two env vars in Vercel:
//   CRM_APPLICATIONS_URL   e.g. https://crm.ssyogaretreats.com/api/applications
//   CRM_APPLICATIONS_TOKEN a bearer token/API key generated by the CRM
// This function is a no-op (logs only) until both are set, so nothing here
// breaks or silently fails while that connection is being finalized.
async function sendToCrm(payload: Record<string, unknown>) {
  const url = process.env.CRM_APPLICATIONS_URL;
  const token = process.env.CRM_APPLICATIONS_TOKEN;

  if (!url || !token) {
    console.log(
      "[CRM] Not configured yet — application logged locally only:",
      payload
    );
    return { delivered: false };
  }

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    console.error("[CRM] Failed to deliver application:", await res.text());
    return { delivered: false };
  }

  return { delivered: true };
}
// ------------------------------------------------------------------------

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null);

  if (!body) {
    return NextResponse.json({ error: "Invalid submission." }, { status: 400 });
  }

  const missing = REQUIRED_FIELDS.filter((field) => !body[field]);
  if (missing.length > 0) {
    return NextResponse.json(
      { error: `Missing required fields: ${missing.join(", ")}` },
      { status: 400 }
    );
  }

  const payload = {
    fullName: body.fullName,
    email: body.email,
    phone: body.phone,
    instagram: body.instagram || null,
    retreat: body.retreat,
    roomPreference: body.roomPreference || null,
    experienceLevel: body.experienceLevel || null,
    dietary: body.dietary || null,
    emergencyContactName: body.emergencyContactName,
    emergencyContactPhone: body.emergencyContactPhone,
    referralSource: body.referralSource || null,
    notes: body.notes || null,
    waiverAcknowledged: Boolean(body.waiverAcknowledged),
    submittedAt: new Date().toISOString(),
    source: "ssyogaretreats.com/application",
  };

  console.log("New retreat application:", payload);

  const crmResult = await sendToCrm(payload);

  return NextResponse.json({ ok: true, crmDelivered: crmResult.delivered });
}
